services:
    fastify:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "3011:3001"
        volumes:
            - ./src:/app/src
        environment:
            - POSTGRESQL_HOST=db
    db:
        image: postgres:12.2
        env_file:
            - .env
        volumes:
            - ./db/data:/var/lib/postgresql/data
